version: '3'

services:
        pgadmin:
                container_name: pgadmin
                image: dpage/pgadmin4
                restart: always
                ports:
                        - "15432:80"
                environment:
                        PGADMIN_DEFAULT_EMAIL: pgadmin
                        PGADMIN_DEFAULT_PASSWORD: pgadmin
        kibana:
                container_name: kibana
                image: kibana:7.16.2
                ports:
                        - "5601:5601"